- name: Install GUI utilities
  become: true
  community.general.pacman:
    name:
      - flatpak
      - wezterm
      - iio-sensor-proxy # enable automatic screen brightness
      - mesa-utils
      - pipewire
      - pipewire-pulse
      - pipewire-jack
      - wireplumber
      - papirus-icon-theme
    state: present
    # Automatically remove conflicting packages
    # (e.g. remove pulseaudio when installing pipewire-pulse)
    # Magical option see: https://unix.stackexchange.com/a/584001
    extra_args: --ask 4 --noconfirm

- name: Add the Flathub flatpak repository remote
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install hardcode tray icon fixer
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    name: hardcode-tray-git
    use: makepkg
    state: present

- name: Install fonts
  become: true
  community.general.pacman:
    name:
      - ttf-hack
      - ttf-font-awesome
      - ttf-dejavu
      - ttf-ibm-plex
      - ttf-roboto
      - noto-fonts
      - noto-fonts-emoji
      - ttf-croscore
      - powerline-fonts
      - ttf-nerd-fonts-symbols-1000-em
    state: present

- name: Setup Drop CTRL key remap (CAPSLOCK -> ESC)
  become: true
  ansible.builtin.template:
    src: files/95-drop-ctrl-caps-esc-remap.hwdb
    dest: /etc/udev/hwdb.d/95-drop-ctrl-caps-esc-remap.hwdb

- name: Setup Framework laptop key remap (CAPSLOCK -> ESC)
  become: true
  ansible.builtin.template:
    src: files/95-framework-caps-esc-remap.hwdb
    dest: /etc/udev/hwdb.d/95-framework-caps-esc-remap.hwdb

- name: Setup Keychron K1 key remap (CAPSLOCK -> ESC)
  become: true
  ansible.builtin.template:
    src: files/95-keychron-k1-caps-esc-remap.hwdb
    dest: /etc/udev/hwdb.d/95-keychron-k1-caps-esc-remap.hwdb

- name: Setup Lenovo external keyboard key remap (CAPSLOCK -> ESC)
  become: true
  ansible.builtin.template:
    src: files/95-lenovo-external-caps-esc-remap.hwdb
    dest: /etc/udev/hwdb.d/95-lenovo-external-caps-esc-remap.hwdb
