- name: Install fonts
  become: true
  community.general.pacman:
    name:
      - ttf-hack
      - ttf-font-awesome
      - ttf-dejavu
      - ttf-ibm-plex
      - ttf-roboto
      - noto-fonts
      - noto-fonts-emoji
      - ttf-croscore
      - powerline-fonts
    state: present

- name: Installing fonts (AUR)
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    name: ttf-meslo-nerd-font-powerlevel10k
    use: yay

- name: update font-cache
  become: true
  command: fc-cache -fv