- name: Install development GUI utilities
  become: true
  community.general.pacman:
    name:
      - wezterm
      - wireshark-qt
    state: present

- name: Install VS Code
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    name: visual-studio-code-bin
    use: makepkg
    state: present

- name: Configure git - set VS Code as editor
  community.general.git_config:
    name: core.editor
    scope: global
    value: "code --wait"

- name: Configure git - set VS Code as diff tool
  community.general.git_config:
    name: diff.tool
    scope: global
    value: vscode

- name: Configure git - diff command
  community.general.git_config:
    name: difftool.vscode.cmd
    scope: global
    value: "code --wait --diff $LOCAL $REMOTE"

- name: Configure git - set VS Code as merge tool
  community.general.git_config:
    name: merge.tool
    scope: global
    value: vscode

- name: Configure git - merge command
  community.general.git_config:
    name: mergetool.vscode.cmd
    scope: global
    value: "code --wait $MERGED"
