[".vim/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "168h"
["opt/dracula-gnome-terminal"]
    type = "archive"
    url = "https://github.com/dracula/gnome-terminal/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".local/share/gedit/styles/dracula.xml"]
    type = "file"
    url = "https://raw.githubusercontent.com/dracula/gedit/master/dracula.xml"
    refreshPeriod = "168h"
[".local/share/themes/Dracula"]
    type = "archive"
    exact = true
    url = "https://github.com/dracula/gtk/archive/master.tar.gz"
    stripComponents = 1
    refreshPeriod = "168h"