#!/usr/bin/env bash

set -e

usage() {
  __USAGE="
 \x1b[34m▶\x1b[0m Theia is a utility for system management tasks.

   \x1b[1mUSAGE\x1b[0m
 \x1b[34m$\x1b[0m theia [GLOBAL_OPTIONS] COMMAND [COMMAND_OPTIONS]

   \x1b[1mCOMMANDS\x1b[0m
 \x1b[34m•\x1b[0m install ……… Run initial setup
 \x1b[34m•\x1b[0m update ………… Update system

   Use \x1b[3mtheia [COMMAND] -h\x1b[0m to get help about each command.
"
  echo -e "$__USAGE" 1>&2 
}

COMMAND=""
ARGS=("$@")
CHEZMOI_PATH="$(chezmoi source-path)"

for ((i=0; i<"${#ARGS[@]}"; ++i)); do
  # Any flags that occur before the command are intended for this script
  if [ "$COMMAND" == "" ]; then
    case "${ARGS[i]}" in
      -h|--help)
        usage
        exit 0
        ;;
      -*|--*=)
        echo "Error: Unsupported flag $1" >&2
        exit 1
        ;;
      *)
        # First argument without a dash is the command
        COMMAND="$1"
        unset ARGS[i];
        ;;
    esac
  fi
done

case "$COMMAND" in
  "")
    usage
    exit 1
    ;;
  install)
    $CHEZMOI_PATH/setup/install.sh "${ARGS[@]}"
    ;;
  update)
    $CHEZMOI_PATH/setup/update.sh "${ARGS[@]}"
    ;;
  *)
    echo "Error: Unsupported command $COMMAND" >&2
    usage
    exit 1
    ;;
esac
