- name: Install Git
  become: true
  community.general.pacman:
    name:
      - git

- name: Configure git
  ansible.builtin.shell: |
    git config --global push.default simple
    git config --global alias.up 'pull --rebase --autostash'
    git config --global diff.tool vscode
    git config --global difftool.vscode.cmd "code --wait --diff \$LOCAL \$REMOTE"
    git config --global merge.tool vscode
    git config --global mergetool.vscode.cmd "code --wait \$MERGED"
    git config --global mergetool.keepBackup false
    git config --global init.defaultBranch main