- name: Install Git
  become: true
  community.general.pacman:
    name:
      - git

- name: Configure git
  ansible.builtin.shell: |
    git config --global push.default simple
    git config --global alias.up 'pull --rebase --autostash'
    git config --global diff.tool meld
    git config --global merge.tool meld
    git config --global mergetool.meld.cmd "/usr/sbin/meld \"\$LOCAL\" \"\$MERGED\" \"\$REMOTE\" --output \"\$MERGED\""
    git config --global mergetool.keepBackup false
    git config --global init.defaultBranch main