- name: Install Flatpak
  become: true
  community.general.pacman:
    name: flatpak
    state: present

- name: Add the Flathub flatpak repository remote
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install Spotify from Flathub
  community.general.flatpak:
    name: com.spotify.Client
    state: present
