- name: Install Docker
  become: true
  community.general.pacman:
    name:
      - docker
      - docker-compose
    state: present

# Not recommended to launch Docker on boot for desktop systems
# See: https://github.com/moby/moby/issues/38373
- name: Enable Docker socket
  become: true
  shell: |
    systemctl disable docker.service
    systemctl enable docker.socket
