- name: Install CLI utilities
  become: true
  community.general.pacman:
    name:
      - git
      - openssh
      - httpie
      - the_silver_searcher
      - pass
      - htop
      - fzf
      - fasd
      - pwgen
      - wget
      - strace
      - rsync
      - jq
      - net-tools
      - acpi
      - usbutils
      - imagemagick
      - ffmpeg
      - bluez
      - bluez-utils
      - tpm2-tools
      - wireguard-tools
      - dconf
      - gstreamer
      - gst-libav
      - gst-plugins-base
      - gst-plugins-good
      - gst-plugins-ugly
    state: present
