- name: Install CLI utilities
  community.general.pacman:
    name:
      - git
      - httpie
      - the_silver_searcher
      - htop
      - fzf
      - fasd
      - pwgen
      - wget
      - strace
      - rsync
      - jq
    state: present
