- name: Install CLI utilities
  become: true
  community.general.pacman:
    name:
      - openssh
      - httpie
      - ripgrep
      - pass
      - htop
      - fzf
      - fasd
      - fd
      - pwgen
      - wget
      - strace
      - rsync
      - jq
      - net-tools
      - acpi
      - usbutils
      - imagemagick
      - ffmpeg
      - bluez
      - bluez-utils
      - tpm2-tools
      - tpm2-pkcs11
      - wireguard-tools
      - dconf
      - gstreamer
      - gst-libav
      - gst-plugins-base
      - gst-plugins-good
      - gst-plugins-ugly
      - gnupg
      - gnupg-pkcs11-scd
      - pinentry
      - wl-clipboard
      - patch
      - elfutils
      - lsd
      - smartmontools
      - fwupd
      - github-cli
      - zsh
      - zsh-completions
      - zsh-syntax-highlighting
      - zsh-theme-powerlevel10k
      - vim
    state: present

- name: Install Oh My ZSH
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    name: oh-my-zsh-git
    use: makepkg
    state: present

- name: Install VIM plugins
  command: vim +'PlugInstall --sync' +qa
