- name: Install Node.js
  become: true
  community.general.pacman:
    name:
      - nodejs
      - npm
    state: present

- name: Install Yarn
  become: true
  community.general.npm:
    name: yarn
    global: true