- name: Setup user {{ main_user }}
  become: true
  user:
    name: "{{ main_user }}"
    groups: wheel,wireshark,docker,tss,libvirt,lp,kvm
    append: true
    shell: /bin/zsh

- name: Allow members of group wheel to execute any command
  become: true
  lineinfile:
    path: /etc/sudoers.d/10-wheel
    line: '%wheel ALL=(ALL) ALL'
    create: true
    validate: 'visudo -cf %s'
