- name: Install ZSH
  become: true
  community.general.pacman:
    name:
      - zsh
      - zsh-completions
      - zsh-syntax-highlighting
      - zsh-theme-powerlevel10k
    state: present

- name: Install Oh My ZSH
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    name: oh-my-zsh-git
    use: makepkg
    state: present
