- name: Enable dark mode
  community.general.dconf:
    key: /org/gnome/desktop/interface/color-scheme
    value: "'prefer-dark'"
    state: present

- name: Set GTK theme to Dracula
  community.general.dconf:
    key: /org/gnome/desktop/interface/gtk-theme
    value: "'Dracula'"
    state: present

- name: Set Shell theme to Dracula
  community.general.dconf:
    key: /org/gnome/desktop/wm/preferences/theme
    value: "'Dracula'"
    state: present

- name: Set Gedit theme to Dracula
  community.general.dconf:
    key: /org/gnome/gedit/preferences/editor/scheme
    value: "'dracula'"
    state: present

- name: Set icon theme to Papirus
  community.general.dconf:
    key: /org/gnome/desktop/interface/icon-theme
    value: "'Papirus-Dark'"
    state: present

- name: Disable hot corners
  community.general.dconf:
    key: /org/gnome/desktop/interface/enable-hot-corners
    value: "false"
    state: present

- name: Map CAPSLOCK to ESC
  community.general.dconf:
    key: /org/gnome/desktop/input-sources/xkb-options
    value: "['caps:escape_shifted_capslock', 'lv3:ralt_switch']"
    state: present

- name: Find out GNOME Terminal profile ID
  ansible.builtin.shell: gsettings get org.gnome.Terminal.ProfilesList default | awk -F \' '{print $2}'
  register: gnome_terminal_profile
  changed_when: false

- name: Set system-wide monospace font to MonoLisa
  community.general.dconf:
    key: /org/gnome/desktop/interface/monospace-font-name
    value: "'MonoLisa 10'"
    state: present

- name: Set GNOME Terminal font to MonoLisa
  community.general.dconf:
    key: /org/gnome/terminal/legacy/profiles:/:{{ gnome_terminal_profile.stdout }}/font
    value: "'MonoLisa 11'"
    state: present

- name: Disable gnome-keyring-ssh
  shell: |
    echo 'X-GNOME-Autostart-enabled=false' \
      | cat /etc/xdg/autostart/gnome-keyring-ssh.desktop - \
      >> ~/.config/autostart/gnome-keyring-ssh.desktop
  args:
    creates: ~/.config/autostart/gnome-keyring-ssh.desktop

- name: Set GNOME Terminal settings - use system font
  community.general.dconf:
    key: /org/gnome/terminal/legacy/profiles:/:{{ gnome_terminal_profile.stdout }}/use-system-font
    value: "false"
    state: present

- name: Set GNOME Terminal settings - default size columns
  community.general.dconf:
    key: /org/gnome/terminal/legacy/profiles:/:{{ gnome_terminal_profile.stdout }}/default-size-columns
    value: 100
    state: present

- name: Set GNOME Terminal settings - default size rows
  community.general.dconf:
    key: /org/gnome/terminal/legacy/profiles:/:{{ gnome_terminal_profile.stdout }}/default-size-rows
    value: 28
    state: present

- name: Set GNOME Terminal settings - color palette
  community.general.dconf:
    key: /org/gnome/terminal/legacy/profiles:/:{{ gnome_terminal_profile.stdout }}/palette
    value: "['#262626', '#E356A7', '#42E66C', '#E4F34A', '#9B6BDF', '#E64747', '#75D7EC', '#EFA554', '#7A7A7A', '#FF79C6', '#50FA7B', '#F1FA8C', '#BD93F9', '#FF5555', '#8BE9FD', '#FFB86C']"
    state: present

- name: Set GNOME Terminal settings - background color
  community.general.dconf:
    key: /org/gnome/terminal/legacy/profiles:/:{{ gnome_terminal_profile.stdout }}/background-color
    value: "'#282A36'"
    state: present

- name: Set GNOME Terminal settings - foreground color
  community.general.dconf:
    key: /org/gnome/terminal/legacy/profiles:/:{{ gnome_terminal_profile.stdout }}/foreground-color
    value: "'#F8F8F2'"
    state: present

- name: Set GNOME Terminal settings - use theme colors
  community.general.dconf:
    key: /org/gnome/terminal/legacy/profiles:/:{{ gnome_terminal_profile.stdout }}/use-theme-colors
    value: "false"
    state: present

- name: Set GNOME Terminal settings - bold color same as foreground
  community.general.dconf:
    key: /org/gnome/terminal/legacy/profiles:/:{{ gnome_terminal_profile.stdout }}/bold-color-same-as-fg
    value: "true"
    state: present

- name: Lock system five seconds after screensaver triggers
  community.general.dconf:
    key: /org/gnome/desktop/screensaver/lock-delay
    value: "uint32 5"
    state: present
