- name: Set GTK theme to Dracula
  community.general.dconf:
    key: /org/gnome/desktop/interface/gtk-theme
    value: "'Dracula'"
    state: present

- name: Set Shell theme to Dracula
  community.general.dconf:
    key: /org/gnome/desktop/wm/preferences/theme
    value: "'Dracula'"
    state: present

- name: Set Gedit theme to Dracula
  community.general.dconf:
    key: /org/gnome/gedit/preferences/editor/scheme
    value: "'Dracula'"
    state: present

- name: Map CAPSLOCK to ESC
  community.general.dconf:
    key: /org/gnome/desktop/input-sources/xkb-options
    value: "['caps:escape_shifted_capslock', 'lv3:ralt_switch']"
    state: present

- name: Find out GNOME Terminal profile ID
  ansible.builtin.shell: gsettings get org.gnome.Terminal.ProfilesList default | awk -F \' '{print $2}'
  register: gnome_terminal_profile
  changed_when: false

- name: Install Dracula GNOME Terminal theme
  ansible.builtin.shell: $HOME/opt/dracula-gnome-terminal/install.sh --profile :{{ gnome_terminal_profile.stdout }} --scheme Dracula --skip-dircolors

- name: Set system-wide monospace font to MonoLisa
  community.general.dconf:
    key: /org/gnome/desktop/interface/monospace-font-name
    value: "'MonoLisa 10'"
    state: present

- name: Set GNOME Terminal font to MonoLisa
  community.general.dconf:
    key: /org/gnome/terminal/legacy/profiles:/{{ gnome_terminal_profile.stdout }}:/font
    value: "'MonoLisa 11'"
    state: present

- name: Disable gnome-keyring-ssh
  shell: |
    echo 'X-GNOME-Autostart-enabled=false' \
      | cat /etc/xdg/autostart/gnome-keyring-ssh.desktop - \
      >> ~/.config/autostart/gnome-keyring-ssh.desktop
  args:
    creates: ~/.config/autostart/gnome-keyring-ssh.desktop

- name: Set GNOME Terminal settings - Use system font
  community.general.dconf:
    key: /org/gnome/terminal/legacy/profiles:/{{ gnome_terminal_profile.stdout }}:/use-system-font
    value: "false"
    state: present

- name: Set GNOME Terminal settings - Default size columns
  community.general.dconf:
    key: /org/gnome/terminal/legacy/profiles:/{{ gnome_terminal_profile.stdout }}:/default-size-columns
    value: 100
    state: present

- name: Set GNOME Terminal settings - Default size rows
  community.general.dconf:
    key: /org/gnome/terminal/legacy/profiles:/{{ gnome_terminal_profile.stdout }}:/default-size-rows
    value: 28
    state: present

- name: Set GNOME Terminal settings - Bold color same as foreground
  community.general.dconf:
    key: /org/gnome/terminal/legacy/profiles:/{{ gnome_terminal_profile.stdout }}:/bold-color-same-as-fg
    value: "true"
    state: present

- name: Lock system five seconds after screensaver triggers
  community.general.dconf:
    key: /org/gnome/desktop/screensaver/lock-delay
    value: "uint32 5"
    state: present
