- name: Set GTK theme to Dracula
  ansible.builtin.shell: |
    gsettings set org.gnome.desktop.interface gtk-theme "Dracula"
    gsettings set org.gnome.desktop.wm.preferences theme "Dracula"

- name: Map CAPSLOCK to ESC
  command: gsettings set org.gnome.desktop.input-sources xkb-options "['caps:escape_shifted_capslock','lv3:ralt_switch']"

- name: Lock system five seconds after screensaver triggers
  command: gsettings set org.gnome.desktop.screensaver lock-delay 5

- name: Set gedit theme to Dracula
  command: gsettings set org.gnome.gedit.preferences.editor scheme 'dracula'

- name: Set monospace font to MonoLisa
  command: gsettings set org.gnome.desktop.interface monospace-font-name 'MonoLisa 10'

- name: Disable gnome-keyring-ssh
  shell: |
    echo 'X-GNOME-Autostart-enabled=false' \
      | cat /etc/xdg/autostart/gnome-keyring-ssh.desktop - \
      >> ~/.config/autostart/gnome-keyring-ssh.desktop
  args:
    creates: ~/.config/autostart/gnome-keyring-ssh.desktop

- name: Find out GNOME Terminal profile ID
  ansible.builtin.shell: gsettings get org.gnome.Terminal.ProfilesList default | awk -F \' '{print $2}'
  register: gnome_terminal_profile

- name: Install Dracula GNOME Terminal theme
  ansible.builtin.shell: $HOME/opt/dracula-gnome-terminal/install.sh --profile :{{ gnome_terminal_profile.stdout }} --scheme Dracula --skip-dircolors

- name: Set GNOME Terminal settings
  ansible.builtin.shell: |
    gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:{{ gnome_terminal_profile.stdout }}/ font 'MonoLisa 11'
    gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:{{ gnome_terminal_profile.stdout }}/ use-system-font false
    gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:{{ gnome_terminal_profile.stdout }}/ default-size-columns 100
    gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:{{ gnome_terminal_profile.stdout }}/ default-size-rows 28
    gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:{{ gnome_terminal_profile.stdout }}/ bold-color-same-as-fg true