- name: Set GTK theme
  command: gsettings set org.gnome.desktop.interface gtk-theme "Adwaita-dark"

- name: Map CAPSLOCK to ESC
  command: gsettings set org.gnome.desktop.input-sources xkb-options "['caps:swapescape','lv3:ralt_switch']"

- name: Lock system five seconds after screensaver triggers
  command: gsettings set org.gnome.desktop.screensaver lock-delay 5

- name: Set gedit theme to Dracula
  command: gsettings set org.gnome.gedit.preferences.editor scheme 'dracula'

- name: Set monospace font to MonoLisa
  command: gsettings set org.gnome.desktop.interface monospace-font-name 'MonoLisa 10'