- name: Install GUI utilities
  become: true
  community.general.pacman:
    name:
      - firefox
      - wireshark-qt
      - gimp
      - inkscape
      # Enable automatic screen brightness
      - iio-sensor-proxy
      - mesa-utils
      - pipewire
      - pipewire-pulse
      - pipewire-jack
      - wireplumber
    state: present
    # Automatically remove conflicting packages
    # (e.g. remove pulseaudio when installing pipewire-pulse)
    # Magical option see: https://unix.stackexchange.com/a/584001
    extra_args: --ask 4 --noconfirm