- name: Install GUI utilities
  become: true
  community.general.pacman:
    name:
      - firefox
      - wireshark-qt
      - gimp
      - inkscape
      # Enable automatic screen brightness
      - iio-sensor-proxy
    state: present

