- hosts: all
  roles:
    - arch/yay
    - arch/cli-utils

- hosts: gui
  roles:
    - arch/gui
    - arch/kvm-guest
    - arch/gnome

- hosts: dev
  vars:
    main_user: "{{ ansible_user_id }}"
  roles:
    - arch/dev-cli

- hosts: dev:&gui
  roles:
    - arch/dev-gui

- hosts: creative:&gui
  roles:
    - arch/creative-gui

- hosts: social:&gui
  roles:
    - linux/social-flatpak

- hosts: entertainment:&gui
  roles:
    - linux/entertainment-flatpak

- hosts: all
  vars:
    main_user: "{{ ansible_user_id }}"
  roles:
    - arch/user
