- hosts: all
  roles:
    - arch/yay
    - arch/cli-utils

- hosts: gui
  roles:
    - arch/gui
    - arch/kvm-guest
    - arch/gnome
    - arch/flatpak

- hosts: dev
  roles:
    - arch/dev-cli

- hosts: dev:&gui
  roles:
    - arch/dev-gui

- hosts: all
  vars:
    main_user: "{{ ansible_user_id }}"
  roles:
    - arch/user
