- hosts: all
  vars:
    main_user: "{{ ansible_user_id }}"
  roles:
    - arch/git
    - arch/yay
    - arch/node
    - arch/cli-utils
    - arch/node-utils
    - arch/zsh
    - arch/docker
    - arch/go
    - arch/vim
    - arch/user

- hosts: gui
  roles:
    - arch/code
    - arch/gui-utils
    - arch/kvm-guest
    - arch/gnome-terminal
    - arch/fonts
    - arch/gnome
    - arch/flatpak