- name: Install Git
  become: true
  community.general.pacman:
    name:
      - git
      - docker
      - docker-compose
      - kubectl
      - nodejs
      - npm
      - go

- name: Configure git - default push action
  community.general.git_config:
    name: push.default
    scope: global
    value: simple

- name: Configure git - 'git up' alias
  community.general.git_config:
    name: alias.up
    scope: global
    value: 'pull --rebase --autostash'

- name: Configure git - set VS Code as diff tool
  community.general.git_config:
    name: diff.tool
    scope: global
    value: vscode

- name: Configure git - diff command
  community.general.git_config:
    name: difftool.vscode.cmd
    scope: global
    value: "code --wait --diff $LOCAL $REMOTE"

- name: Configure git - set VS Code as merge tool
  community.general.git_config:
    name: merge.tool
    scope: global
    value: vscode

- name: Configure git - merge command
  community.general.git_config:
    name: mergetool.vscode.cmd
    scope: global
    value: "code --wait $MERGED"

- name: Configure git - automatically clean up backups
  community.general.git_config:
    name: mergetool.keepBackup
    scope: global
    value: 

- name: Configure git - default branch 'main'
  community.general.git_config:
    name: init.defaultBranch
    scope: global
    value: main

- name: Install Yarn
  become: true
  community.general.npm:
    name: yarn
    global: true

- name: Disable yarn telemetry
  command: yarn config set --home enableTelemetry 0

- name: Install CLI utilities - http-server (NPM)
  become: true
  community.general.npm:
    name: http-server
    global: true

- name: Install CLI utilities - zx (NPM)
  become: true
  community.general.npm:
    name: zx
    global: true

- name: Install CLI utilities - npm-check-updates (NPM)
  become: true
  community.general.npm:
    name: npm-check-updates
    global: true

- name: Install CLI utilities - madge (NPM)
  become: true
  community.general.npm:
    name: madge
    global: true

# Not recommended to launch Docker on boot for desktop systems
# See: https://github.com/moby/moby/issues/38373
- name: Enable Docker socket
  become: true
  shell: |
    systemctl disable docker.service
    systemctl enable docker.socket
